### ISSUE TITLE
No controlas las fechas de años bisiestos

### ISSUE THREAD

**Issue by Sadidadri** [Arizaser/reentrega-examen-js-diciembre#2]
https://github.com/Arizaser/reentrega-examen-js-diciembre/blob/ad51cf26d2623028234da01edd5cab751042d738/js/Validar.js#L29

**Comment by lmagarin** [comment]
@Sadidadri @Arizaser Sigues sin controlar las fechas. Lo hemos visto en clase. Deberías haberlo rectificado
